
/*!
 * @file
 * @brief Configuration generated by MCUXpresso
 */

#include "fsl_common.h"
#include "fsl_power.h"
#include "fsl_clock.h"
#include "clock.h"

void clock_init(void)
{
  POWER_DisablePD(kPDRUNCFG_PD_FRO192M);
  CLOCK_SetupFROClocking(12000000U);
  CLOCK_AttachClk(kFRO12M_to_MAIN_CLK);

  SYSCON->CLOCK_CTRL |= SYSCON_CLOCK_CTRL_FRO1MHZ_CLK_ENA_MASK;

  CLOCK_SetupFROClocking(96000000U);

  POWER_SetVoltageForFreq(96000000U);
  CLOCK_SetFLASHAccessCyclesForFreq(96000000U);

  CLOCK_SetClkDiv(kCLOCK_DivAhbClk, 1U, false);
  CLOCK_SetClkDiv(kCLOCK_DivArmTrClkDiv, 0U, true);
  CLOCK_SetClkDiv(kCLOCK_DivArmTrClkDiv, 1U, false);
  CLOCK_SetClkDiv(kCLOCK_DivSystickClk0, 0U, true);
  CLOCK_SetClkDiv(kCLOCK_DivSystickClk0, 1U, false);
  CLOCK_SetClkDiv(kCLOCK_DivFrohfClk, 0U, true);
  CLOCK_SetClkDiv(kCLOCK_DivFrohfClk, 1U, false);
  CLOCK_SetClkDiv(kCLOCK_DivWdtClk, 0U, true);
  CLOCK_SetClkDiv(kCLOCK_DivWdtClk, 10U, false);
  CLOCK_SetClkDiv(kCLOCK_DivFro1mClk, 0U, true);
  CLOCK_SetClkDiv(kCLOCK_DivFro1mClk, 32U, false);
  CLOCK_SetClkDiv(kCLOCK_DivCanClk, 0U, true);
  CLOCK_SetClkDiv(kCLOCK_DivCanClk, 1U, false);

  CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);

  SystemCoreClockUpdate();
}
